print(f'======== DESAFIO 7 - MÉDIA DO ALUNO ========')
nome = input('Digite o nome do aluno: ')
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
print(f'A média das notas de {nome} foi de {(nota1+nota2)/2} pontos')
