print('======= DESAFIO 12 - DESCONTO DE UM PRODUTO =======')
vi = float(input('Digite o preço do produto: R$'))
vf = vi - vi*(0.05)
print()
print(f'Você foi premiado(a) com 5% de desconto no seu produto!')
print(f'Agora você irá pagar apenas R${vf:.2f} reais.')
